### ISSUE TITLE
compile_time attribute in chef_gem resource breaks on chef < 12.1

### ISSUE THREAD

**Issue by jameslegg** [opscode-cookbooks/aws#107]
the changes in 2.6.1 from [https://github.com/opscode-cookbooks/aws/commit/2fc04a4f5e45494da6e27a5246789d8b17797cf2] Intended to suppress the warnings from the newer compile_time resource on chef_gem break the cookbook if you are not using chef 12.1 (which isn't out yet anyway).

This fixes https://github.com/opscode-cookbooks/aws/pull/106

pinging @someara who has made a few of these changes recently ;)

**Comment by someara** [comment]
Sorry about that. Fixed in the latest patch release

**Comment by jameslegg** [comment]
NP, thanks for the quick fix. :thumbsup:

**Comment by scalp42** [comment]
@someara it's not fixed for us as the resource does not see it.

Also related to https://github.com/opscode-cookbooks/xml/issues/22
